compiler = "gyc"
license = "proprietary"
authors = ["Emile Cadorel <ecadorel@gmail.com>"]
description = "Ymir 3D engine using Vulkan and GLFW"
version = "0.1.22"
name = "Balder"

[targets.balder]
type = "library"
description = "The Balder engine"
package-root = "balder"
output = "Balder"
dependencies = ["yassimp", "ysdl3", "yvulkan", "yharfbuzz"]
libraries = ["SDL3", "SDL3_image", "vulkan", "assimp", "harfbuzz", "freetype"]

[targets.demo]
type = "executable"
description = "A 3D scene with a few widgets on top of it"
source-dir = "example/demo"
package-root = "main"
tests = false
libraries = ["SDL3", "SDL3_image", "vulkan", "assimp", "harfbuzz", "freetype"]
targets = ["balder"]

[targets.form]
type = "executable"
description = "An input form, to try the input texts"
source-dir = "example/form"
package-root = "main"
tests = false
libraries = ["SDL3", "SDL3_image", "vulkan", "assimp", "harfbuzz", "freetype"]
targets = ["balder"]

[dependencies]
yassimp = {version = "master", url = {git = "git@github.com:Kag-k-thun/bindy-assimp.git"}}
ysdl3 = {version = "master", url = {git = "git@github.com:Kag-k-thun/bindy-sdl3.git"}}
yvulkan = {version = "master", url = {git = "git@github.com:Kag-k-thun/bindy-vulkan.git"}}
yharfbuzz = {version = "master", url = {git = "git@github.com:Kag-k-thun/bindy-harfbuzz.git"}}

[registry]
local = "/home/emile/.local/gyllir/Balder"

[commands]
shader_compile = { cmd = "./compile.sh", post = false, cwd = "./res/shaders" }
