depth = true

[pass.vertex]
index = 0
shader = "shaders:/triangle/triangle.vert.spv"

[pass.fragment]
index = 1
shader = "shaders:/triangle/triangle.frag.spv"

[uniform.world]
binding = 0
size = 64 # 3 * mat4

[uniform.camera]
binding = 1
size = 128 # 3 * mat4

[texture.albedo]
binding = 2
kind = "albedo"

[texture.depth]
binding = 3
kind = "depth"
