[pass.vertex]
index = 0
shader = "shaders:/white/white.vert.spv"

# [pass.fragment]
# index = 1
# shader = "shaders:/white/white.frag.spv"

[uniform.world]
binding = 0
size = 64 # 3 * mat4

[uniform.camera]
binding = 1
size = 128 # 3 * mat4
