kind = "compute"

[local-groups]
x = 8
y = 8
z = 1

[pass.compute]
index  = 0
shader = "shaders:/base/3D/environment/downsample.comp.spv"

# ====================================================================================================
# ====================================================================================================
# =====================================          OUTPUT          =====================================
# ====================================================================================================
# ====================================================================================================

# the faces of a level of the environment cube
[set.global.storage-texture.output]
binding = 0

# the faces of the level before it, twice as large, read texel by texel
[set.global.storage-texture.input]
binding = 1
