kind = "compute"

[local-groups]
x = 8
y = 8
z = 1

[pass.compute]
index  = 0
shader = "shaders:/base/3D/environment/brdf.comp.spv"

# ====================================================================================================
# ====================================================================================================
# =====================================          OUTPUT          =====================================
# ====================================================================================================
# ====================================================================================================

# the scale and the bias of the reflectance facing the eye, by the cosine to the eye (x) and the roughness (y)
[set.global.storage-texture.output]
binding = 0
