kind = "compute"

[local-groups]
x = 8
y = 8
z = 1

[pass.compute]
index  = 0
shader = "shaders:/base/3D/environment/irradiance.comp.spv"

# ====================================================================================================
# ====================================================================================================
# =====================================          OUTPUT          =====================================
# ====================================================================================================
# ====================================================================================================

# the faces of the irradiance, the light a white diffuse surface facing each direction reflects
[set.global.storage-texture.output]
binding = 0

# ====================================================================================================
# ====================================================================================================
# ====================================          TEXTURES          ====================================
# ====================================================================================================
# ====================================================================================================

# the environment cube, and its levels
[set.global.texture.environment]
binding     = 1
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "linear"
mag-filter  = "linear"
min-filter  = "linear"
max-lod     = 16.0
anisotropy  = false
