kind = "compute"

[local-groups]
x = 8
y = 8
z = 1

[pass.compute]
index  = 0
shader = "shaders:/base/3D/environment/prefilter.comp.spv"

# ====================================================================================================
# ====================================================================================================
# =====================================          OUTPUT          =====================================
# ====================================================================================================
# ====================================================================================================

# the faces of a level of the prefiltered environment
[set.global.storage-texture.output]
binding = 0

# ====================================================================================================
# ====================================================================================================
# ====================================          TEXTURES          ====================================
# ====================================================================================================
# ====================================================================================================

# the environment cube, and its levels
[set.global.texture.environment]
binding     = 1
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "linear"
mag-filter  = "linear"
min-filter  = "linear"
max-lod     = 16.0
anisotropy  = false

# ====================================================================================================
# ====================================================================================================
# =======================================          PC          =======================================
# ====================================================================================================
# ====================================================================================================

# the perceptual roughness of the level written
[push.level]
offset = 0
size   = 4
