log-filter = ["Widget", "Swapchain", "Texture2D", "Window", "Memory", "GarbageBin", "VulkanPipeline", "VulkanTransferPass"]

[window]
name = "Input form"
width = {relative = 0.3, min = 520}
height = {relative = 0.35, min = 380}
resizable = true
vsync = true
