log-filter = ["Widget", "Swapchain", "Texture2D", "Window", "Memory", "GarbageBin", "VulkanPipeline", "VulkanTransferPass"]

[window]
name = "Input form"
width = 520
height = 380
resizable = true
vsync = true
