log-filter = ["Widget", "Swapchain", "Texture2D", "Window", "Memory", "GarbageBin", "VulkanPipeline", "VulkanTransferPass", "Device"]

[window]
name = "Widget gallery"
width = {relative = 0.6, min = 960}
height = {relative = 0.6, min = 640}
resizable = true

[vulkan]
version = 13
anisotropy = true
image-count = 3
vsync = true

[timer]
fps = 30
ips = 30
interactive = true
