style = "res:/config/style.toml"

[gui.A]
kind = "floating_layout"
style = "out_layout"
hover-style = "out_layout"

[gui.A.childs.B]
kind = "box"

[gui.A.childs.C]
kind = "box"

[gui.A.childs.D]
kind = "linear_layout"
hover-style = "linear.linear-hover"
scrollbar-style = "scroll"
scrollbar-size = 5
scrollbar-hover-style = "scroll.scroll-hover"
scrollbar-focus-style = "scroll.scroll-focus"
style = "linear"
x = { relative = 0.01 }
y = { relative = 0.01 }
width = { relative = 0.98 }
height = { relative = 0.98 }
level = 1
scrollable = true
vertical = false

[gui.A.childs.D.childs.Input]
kind = "input"
style = "default.fps-label"
focus-style = "default.fps-label"
hover-style = "default.fps-label"
xalign = "right"
size = { relative = 0.2 }
level = 4

[gui.A.childs.D.childs.Input2]
kind = "input"
level = 0
size = { relative = 0.2 }

[gui.A.childs.D.childs.Input3]
kind = "input"
size = { relative = 0.2 }

[gui.A.childs.D.childs.Input4]
kind = "input"
size = { relative = 0.2 }

[gui.A.childs.D.childs.Input5]
kind = "input"
size = { relative = 0.2 }

[gui.A.childs.D.childs.Input6]
kind = "input"
size = { relative = 0.2 }

[gui.A.childs.back_fps]
kind = "floating_layout"
style = "back-fps"
with-events = false
x = 20
y = 20
width = 200
height = 40
level = 2

[gui.A.childs.back_fps.childs.FPS_LABEL]
kind = "label"
style  = "default.fps-label"
text = "Hello World"
xalign = "left"
yalign = "top"
