[default]
background-color = "grey!10"
border-color = "green!90"
text-color = "grey!100"
selection-color = "#48cae4"
font = "res:/fonts/DejaVuSansMono.ttf"
radius = 5

font-size = 15
border-style = "dotted"
border = 1
padding = 0
margin = 0

[box-hover]
background-color = "purple!20"

[input_text]
font = "res:/fonts/monospace.ttf"
font-size = 50
selection-color = "purple!10"

[input_text-focus]
border-color = "blue!10"
border-style = "solid"

[input_text-hover]
border-color = "blue!30"
border-style = "solid"

[linear]
margin = 0
padding-right = 5
padding = 0
border = 1
border-color="blue!80"
background-color="grey!20"

[linear-hover]
border-color="blue!90"
background-color="grey!30"

[out_layout]
margin = 0
border = 0
padding = 20
background-color = "blue!100"

[fps-label]
font = "res:/fonts/calibri.ttf"
text-color = "green!90"
font-size = 40
selection-color = "blue!1"

[back-fps]
border = 0
margin = 0
padding = 0
background-color = "blue!50;0.2"

[scroll]
background-color = "grey!90"

[scroll-hover]
background-color = "blue!40"

[scroll-focus]
background-color = "blue!80"
