kind = "raster"
depth = true

[blend]
enabled = true

[vertex]
positions = "vec2"

[pass.vertex]
index = 0
shader = "shaders:/base/2D/color/color.vert.spv"

[pass.fragment]
index = 1
shader = "shaders:/base/2D/color/color.frag.spv"


# the dimension of the framebuffer in CSS pixels, then the number of framebuffer pixels in a CSS pixel
[push.window]
offset = 0
size = 16

# the position, the size, the color, the scissors and the level of the shapes, read at the instance of their draws
[set.object.buffer.objects]
binding = 0
