depth = true

[blend]
enabled = true

[vertex]
positions = "vec2"
tex_uv = "vec2"

[pass.vertex]
index = 0
shader = "shaders:/base/2D/texture/texture.vert.spv"

[pass.fragment]
index = 1
shader = "shaders:/base/2D/texture/texture.frag.spv"

[uniform.world]
binding = 0
size = 80

[texture.albedo]
binding = 1
kind = "albedo"
# addressMode = "clamp-edge"
# mipmap = "linear"
# anisotropy = false
