kind = "compute"

[local-groups]
x = 16
y = 16
z = 1

[pass.compute]
index  = 0
shader = "shaders:/base/3D/post/fxaa/fxaa.comp.spv"

# ====================================================================================================
# ====================================================================================================
# =====================================          OUTPUT          =====================================
# ====================================================================================================
# ====================================================================================================

# the colours of the screen, their edges smoothed, encoded in sRGB
[set.global.storage-texture.output]
binding = 0

# ====================================================================================================
# ====================================================================================================
# ====================================          TEXTURES          ====================================
# ====================================================================================================
# ====================================================================================================

# the colours of the screen, written by the pass before it, sampled between the texels along the edges
[set.global.texture.input]
binding     = 1
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "near"
mag-filter  = "linear"
min-filter  = "linear"
anisotropy  = false

# ====================================================================================================
# ====================================================================================================
# ====================================          UNIFORM          =====================================
# ====================================================================================================
# ====================================================================================================

# the thresholds of the edges and the share of the sub-pixel smoothing (see the Params block of the shader)
[set.global.uniform.params]
binding = 2
size    = 16
