kind = "compute"

[local-groups]
x = 16
y = 16
z = 1

[pass.compute]
index  = 0
shader = "shaders:/base/3D/post/invert/invert.comp.spv"

# ====================================================================================================
# ====================================================================================================
# =====================================          OUTPUT          =====================================
# ====================================================================================================
# ====================================================================================================

# the colours of the screen inverted, encoded in sRGB
[set.global.storage-texture.output]
binding = 0

# ====================================================================================================
# ====================================================================================================
# ====================================          TEXTURES          ====================================
# ====================================================================================================
# ====================================================================================================

# the colours of the screen, encoded in sRGB, written by the pass before it, read texel by texel
[set.global.texture.input]
binding     = 1
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "near"
mag-filter  = "near"
min-filter  = "near"
anisotropy  = false
