kind = "compute"

[local-groups]
x = 16
y = 16
z = 1

[pass.compute]
index  = 0
shader = "shaders:/base/3D/post/lut/lut.comp.spv"

# ====================================================================================================
# ====================================================================================================
# =====================================          OUTPUT          =====================================
# ====================================================================================================
# ====================================================================================================

# the colours of the screen graded, encoded in sRGB
[set.global.storage-texture.output]
binding = 0

# ====================================================================================================
# ====================================================================================================
# ====================================          TEXTURES          ====================================
# ====================================================================================================
# ====================================================================================================

# the colours of the screen, written by the pass before it, read texel by texel
[set.global.texture.input]
binding     = 1
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "near"
mag-filter  = "near"
min-filter  = "near"
anisotropy  = false

# the lookup table, a 3D texture interpolated between its entries
[set.global.texture.lut]
binding     = 2
kind        = "albedo"
addressMode = "clamp-edge"
mipmap      = "near"
mag-filter  = "linear"
min-filter  = "linear"
anisotropy  = false

# ====================================================================================================
# ====================================================================================================
# ====================================          UNIFORM          =====================================
# ====================================================================================================
# ====================================================================================================

# the share of the grading (see the Params block of the shader)
[set.global.uniform.params]
binding = 3
size    = 16
